Docker
irynamekh/bookstore pull request #10
Opened 2023-09-27 13:44 UTC by irynamekh

2023-09-27 14:31 UTC, JeniaSan commented on docker-compose.yaml
> +      - $DEBUG_PORT:$DEBUG_PORT
add empty line to the end of the file)

2023-09-27 14:34 UTC, JeniaSan commented on src/main/java/com/bookstore/controller/OrderController.java
> +        return orderService.save(requestDto, user.getId());
You can do transformation logic in the service. 
```suggestion
        return orderService.save(requestDto, authentication);
```

2023-09-27 14:36 UTC, JeniaSan approved these changes
Good job, but I left some comments

2023-09-28 07:23 UTC, nacenik requested changes
GJ, Let's add some improvements

2023-09-28 07:23 UTC, nacenik commented on .env
> +DEBUG_PORT=5005
empty line

2023-09-28 07:23 UTC, nacenik commented on Dockerfile
> +EXPOSE 8080
empty line

2023-09-29 14:47 UTC, vovasalyha approved these changes

2023-10-01 08:55 UTC, merged