Security
irynamekh/bookstore pull request #6
Opened 2023-09-13 20:50 UTC by irynamekh

2023-09-14 21:05 UTC, ohatsenko approved these changes

2023-09-15 07:37 UTC, nacenik requested changes
Good solution! Let's improve your code :)

2023-09-15 07:37 UTC, nacenik commented on pom.xml
> +            <version>0.11.5</version>
add this version as property and reuse it

2023-09-15 07:37 UTC, nacenik commented on pom.xml
> +            <version>2.2.9</version>
use starter `springdoc-openapi-starter-webmvc-ui` and put version as property

2023-09-15 07:37 UTC, nacenik commented on src/main/java/com/bookstore/BookstoreApplication.java
> +@EnableWebMvc
do you really need this annotation?

2023-09-15 07:37 UTC, nacenik commented on src/main/java/com/bookstore/dto/user/UserLoginResponseDto.java
> +    }
do you really need this constructor when you are using `@Data` annotation?

2023-09-15 07:37 UTC, nacenik commented on src/main/java/com/bookstore/dto/user/UserRegistrationRequestDto.java
> +@FieldMatch
which fields should match?

2023-09-15 07:37 UTC, nacenik commented on src/main/java/com/bookstore/exception/CustomGlobalExceptionHandler.java
> +                HttpStatus.BAD_REQUEST, List.of(ex.getMessage()));
I'd recommend you throw 409 instead of 400

2023-09-15 07:37 UTC, nacenik commented on src/main/java/com/bookstore/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(responseBody, HttpStatusCode.valueOf(exceptionStatus));
better to not hardcode the status code. You can use `HttpStatus.CODE_NAME.value()`
```suggestion
        return new ResponseEntity<>(responseBody, HttpStatus.CODE_NAME.value());
```

2023-09-15 07:37 UTC, nacenik commented on src/main/java/com/bookstore/security/CustomUserDetailsService.java
> +                new RuntimeException("Can't find user by email"));
better throw custom exception or `NoSuchElementException`

2023-09-15 07:37 UTC, nacenik commented on src/main/java/com/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
create a constant for value `"Bearer "` and use method `.length()` for substring instead of hardcode the int

2023-09-15 07:37 UTC, nacenik commented on src/main/java/com/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
create a constant for this value

2023-09-18 12:11 UTC, andrii-hoienko requested changes
Nice, I left minor comments

2023-09-18 12:11 UTC, andrii-hoienko commented on src/main/java/com/bookstore/dto/user/UserRegistrationRequestDto.java
> +@FieldMatch(password = "password", repeatPassword = "repeatPassword")
What if you will need to use this annotation for other fields not password and repeatPassword? should properties name be linked to password and repeatPassword?

2023-09-18 12:11 UTC, andrii-hoienko commented on src/main/java/com/bookstore/security/CustomUserDetailsService.java
> +                new NoSuchElementException("Can't find user by email"));
Please add details to error message

2023-09-18 12:11 UTC, andrii-hoienko commented on src/main/java/com/bookstore/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
Is it possible to avoid using @Query?

2023-09-18 12:11 UTC, andrii-hoienko commented on src/main/java/com/bookstore/service/user/UserServiceImpl.java
> +            throw new RegistrationException("User with such an email "
add details to error message

2023-09-20 12:17 UTC, andrii-hoienko approved these changes
GJ!

2023-09-25 17:24 UTC, merged