added a category model and the functionality associated with it
irynamekh/bookstore pull request #7
Opened 2023-09-17 15:05 UTC by irynamekh

2023-09-17 17:04 UTC, Zel1oy approved these changes
Good

2023-09-17 17:04 UTC, Zel1oy commented on src/main/java/com/bookstore/service/book/BookServiceImpl.java
> +    private boolean isUpdateDataPresent(BookRequestDto bookRequestDto) {
Do you really need this method?

2023-09-18 15:42 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-18 15:42 UTC, vovasalyha commented on src/main/java/com/bookstore/service/book/BookServiceImpl.java
> +        if (bookRequestDto.getIsbn() != null) {
All those validations should be in dto

2023-09-18 15:42 UTC, vovasalyha commented on src/main/java/com/bookstore/service/book/BookServiceImpl.java
> +    private boolean isUpdateDataPresent(BookRequestDto bookRequestDto) {
Agree, it can be removed

2023-09-18 15:42 UTC, vovasalyha commented on src/main/java/com/bookstore/service/category/CategoryServiceImpl.java
> +        if (categoryDto == null || !isUpdateDataPresent(categoryDto)) {
Please move all possible fields validations to dtos to not clutter your business code with it

2023-09-18 15:42 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/07-create-book_category-table.yaml
> +            columns:
add also constraint primary key(book_id, category_id)

2023-09-22 12:14 UTC, andrii-hoienko requested changes
GJ, I left minor comments

2023-09-22 12:14 UTC, andrii-hoienko commented on src/main/java/com/bookstore/mapper/BookMapper.java
> +                .map(l -> {
```suggestion
                .map(id -> {
```

2023-09-22 12:14 UTC, andrii-hoienko commented on src/main/java/com/bookstore/mapper/BookMapper.java
> +                .map(l -> {
Please don`t use symbols which is similar to numbers it could be confusing

2023-09-22 12:14 UTC, andrii-hoienko commented on src/main/java/com/bookstore/dto/category/CategoryRequestDto.java
> +    @NotBlank
NotBlank contains null check, it is not necessary to use NotNull

2023-09-22 12:14 UTC, andrii-hoienko commented on src/main/java/com/bookstore/service/category/CategoryServiceImpl.java
> +                new EntityNotFoundException("Can't update because there is no "
```suggestion
                new EntityNotFoundException("Can't update category because there is no "
```

2023-09-25 12:14 UTC, andrii-hoienko approved these changes
GJ!

2023-09-25 17:25 UTC, merged