added an order function
irynamekh/bookstore pull request #9
Opened 2023-09-22 17:06 UTC by irynamekh

2023-09-22 21:56 UTC, DmytroV95 requested changes
GJ! Left some comments to improve your solution.

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/controller/OrderController.java
> +        return orderService.findAll(pageable);
Use get... naming for all methods on this service and controller levels. Change in others methods.

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/mapper/OrderItemMapper.java
> +    OrderItem fromCartItem(CartItem cartItem);
As for me, it's not informative naming.

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/model/Book.java
> +    private BigDecimal price;//TODO
Do you need this comment here?

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/service/cart/ShoppingCartServiceImpl.java
>                  .findFirst()
I think you can use default method from JPA repository to get cart item. Also, this code used twice, make it as a separate method and reuse it.

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/service/cart/ShoppingCartServiceImpl.java
>                  .findFirst()
Same

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
Make a separate as method and reuse in the code.

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +                .toList();
Do you really need all this code? You can do it like findAllOrders() -> stream ()-> toDto -> toList()

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +        return dto;
I recommend you make a few separate methods to make it more readable.

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +    public OrderResponseDto update(Long id, UpdateStatusRequestDto requestDto) {
```suggestion
    public OrderResponseDto updateOrderStatus(Long id, UpdateStatusRequestDto requestDto) {
```

2023-09-22 21:56 UTC, DmytroV95 commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +                        "Can't find order by id: " + orderId));
This code can be as separate method. You use it few times.

2023-09-25 12:29 UTC, andrii-hoienko requested changes
GJ, but some improvements required

2023-09-25 12:29 UTC, andrii-hoienko commented on src/main/java/com/bookstore/model/OrderItem.java
> +    @OneToOne
Please make it lazy

2023-09-25 12:29 UTC, andrii-hoienko commented on src/main/java/com/bookstore/model/Order.java
> +    @OneToMany(mappedBy = "order")
joinColumn?

2023-09-25 12:29 UTC, andrii-hoienko commented on src/main/java/com/bookstore/repository/OrderRepository.java
> +
```suggestion
```

2023-09-25 12:29 UTC, andrii-hoienko commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +        return orderRepository.findAllByUserId(authentificationService.getUserId()).stream()
Is it possible to not retrieve all orders from database, but just retrieve specific one?

2023-09-25 12:29 UTC, andrii-hoienko commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +                .peek(oi -> oi.setPrice(oi.getPrice().multiply(
Please don`t use 3 same operations in a row, maybe it is possible to create a function and just call it in one peek?

2023-09-25 12:29 UTC, andrii-hoienko commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +        return getOrderById(orderId).getOrderItems().stream()
Is it possible to not retrieve all ordersItems from database, but just retrieve specific one?

2023-09-25 12:29 UTC, andrii-hoienko commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +                .map(c -> c.getBook().getPrice().multiply(BigDecimal.valueOf(c.getQuantity())))
code duplication

2023-09-26 12:44 UTC, andrii-hoienko requested changes
Please resolve all comments

2023-09-26 12:44 UTC, andrii-hoienko commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +                .peek(oi -> oi.setPrice(oi.getPrice().multiply(
not resolved

2023-09-27 15:41 UTC, vovasalyha approved these changes

2023-09-27 15:41 UTC, vovasalyha commented on src/main/java/com/bookstore/service/order/OrderServiceImpl.java
> +                .peek(oi -> saveOrderItem(oi, order))
```suggestion
                .peek(orderItem -> saveOrderItem(oi, order))
```
it would be easier to read

2023-09-28 09:01 UTC, merged